site_name: JRuyi
site_url: http://www.jruyi.org
site_description: A Java framework for easily developing network applications as you wish.

repo_url: https://github.com/jruyi/jruyi.git

pages:
- Home: index.md
- Getting Started: getting-started/index.md
- User Guide: user-guide/index.md

markdown_extensions:
    - toc:
        permalink: 
    - admonition:

copyright: Copyright &copy; 2016 <a href="https://twitter.com/jruyi_org">JRuyi.org</a>
google_analytics: ['UA-46193512-1', 'jruyi.org']
